project:
  name: "UbuntuExec1"

paths:
  data_dir: "data"
  resources_dir: "resources"
  results_dir: "results"
  downloads_dir: "downloads"

dataset:
  geo_accession: "GSE262754"
  raw_tar: "GSE262754_RAW.tar"
  raw_extract_dir: "GSE262754_RAW_extracted"
  manifest_tar: "GSE262754_InfiniumOmniExpress-24v1-3_files.tar.gz"
  manifest_extract_dir: "GSE262754_manifest_extracted"
  manifest_csv_gz: "GPL32421_InfiniumOmniExpress-24v1-3_A1.csv.gz"
  manifest_csv: "GPL32421_InfiniumOmniExpress-24v1-3_A1.csv"

array:
  egt: "InfiniumOmniExpress-24v1-3_A1_ClusterFile.egt"
  bpm: "InfiniumOmniExpress-24v1-3_A1.bpm"
  csv_manifest: "GPL32421_InfiniumOmniExpress-24v1-3_A1.csv"
  gtc_batch: "GEObatch"

reference:
  fasta_name: "hg19.fa"
  fasta_url: "http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz"

iaap:
  tarball_name: "iaap-cli-linux-x64-1.1.0-sha.80d7e5b3d9c1fdfc2e99b472a90652fd3848bbc7.tar.gz"

runtime:
  gc_threshold: 0.15
  dtype: "float32"
  workers: 4
  force_cpu: true
  plot_qc: true
  batch_size: 500000

cnv:
  penncnv_dir: "PennCNV"
  hmmfile: "lib/hhall.hmm"
  minlength: 1000
  minconf: 10
  top_n_plots: 5
  plot_width: 12
  plot_height: 7
  pad_probes: 300

threads:
  install: 8
  idat_to_gtc: 40
  cnv_calling: 8

tools:
  htslib_repo: "https://github.com/samtools/htslib.git"
  bcftools_repo: "https://github.com/samtools/bcftools.git"
  samtools_repo: "https://github.com/samtools/samtools.git"
  gtc2vcf_plugin_base_url: "https://raw.githubusercontent.com/freeseek/gtc2vcf/master"

versions:
  note: "Pin external versions or commits here for reproducibility"
